name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.os }} / Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'

      - name: Linux gyp override
        if: runner.os == 'Linux'
        run: |
          set -e
          includes=$(cat << 'EOF'
          {
            "target_defaults": {
              "conditions": [
                ["OS=='linux'", {
                  'cflags_cc!': [ '-std=gnu++20' ],
                  'cflags_cc': [ '-std=gnu++2a' ],
                }]
              ]
            }
          }
          EOF
          )
          mkdir -p "$HOME/.gyp"
          echo "$includes" > "$HOME/.gyp/include.gypi"

      - name: Install dependencies
        run: npm ci
